### ISSUE TITLE
R5: The system should be able to provide a report based on the data.

### ISSUE THREAD

**Issue by theaman249** [COS301-SE-2022/Team-Utilisation-Monitor#96]

**Comment by L3m0nRoCk** [comment]
Reports can be created via JS and Angular 13.
Source: https://www.positronx.io/angular-pdf-tutorial-export-pdf-in-angular-with-jspdf/

reports can only be generated by an admin. 
two options. reports will be constant in format or the admin can chose what sections should be included in the report

Section Ideas:
- graphs about user performance and overall company utilization
- stats on best and worst performing employees
- stats on total employees
